### ISSUE TITLE
Allow all scripts not working on clean install of extension

### ISSUE THREAD

**Issue by ghost** [infernoboy/JavaScript-Blocker#10]
An issue appears to have been introduced in a recent build of Javascript-Blocker that prevents the "Allow All" scripts option from being used in the extension upon a clean installation (not an upgrade from an earlier version). For example:
1. I install Javascript-Extension and complete setup as directed by instructions. The page refreshes and I start seeing blocked notifications.
2. I visit www.macrumors.com
3. 6 scripts are shown as being blocked.
4. I click the Javascript-Blocker menu beside the location bar to bring up the options.
5. I click the "Allow All" option beside "Blocked: 6" and choose to Save my preference.
6. The page refreshes but the 6 scripts remain blocked.

The only solution I have found is to manually choose to allow each of the 6 scripts one at a time.

I have replicated this behaviour on two Macs that were not previously running Javascript-Blocker. On my iMac that was already running previous builds perfectly, Allow All option works fine - even with the same version as the Macs that can't use it. I have only attempted to install and use Javascript-Blocker on these two other Macs recently.

On the Macs where this doesn't work, I've tried resetting Safari back to default. I have blown away all my settings and preferences by removing the Safari preferences folder, and restarting Safari to rebuild this from scratch. I then attempt to reinstall Javascript-Blocker but the same problem remains I cannot use Allow All.

**Comment by infernoboy** [comment]
Resolved.
