### ISSUE TITLE
button "Save" in "Allow or Hide" options doesn't work

### ISSUE THREAD

**Issue by stonevil** [infernoboy/JavaScript-Blocker#13]
Configuration:
OS X 10.8
Safari Version 6.0 (8536.25)
Website: any

Step by step:
1. Click JavaScript Blocker button in Safari toolbar
2. Click Allow or Hide from JavaScript Blocker window
3. Select Some from options
4. Select required js and click Save
5. BUM! Nothing happens (Window stay open, rules are not changed)

**Comment by infernoboy** [comment]
Is this bug present in the github version or the latest public release?

**Comment by stonevil** [comment]
Latest public release.

Myroslav Rys | myroslav@me.com | Infrastructure and Operations Management Expert
mountain bike, snowboard, *nix

**Comment by infernoboy** [comment]
I'm not seeing this issue with Safari 6 on Mountain Lion. If possible, try again with the beta release which will let you view any errors that may be occurring when clicking Save. A number would appear next to "JavaScript Blocker" header in the popover.
