### ISSUE TITLE
[Safari Popover] - Closes when trying to upload file in popover

### ISSUE THREAD

**Issue by oninross** [infernoboy/JavaScript-Blocker#14]
I have an <input type="file" /> in my Safari Popover.  But everytime I try to click on the button to open the Open File Dialog Box, the Extension closes with the dialog box or it doesn't get opened at all.  Any advices?

**Comment by infernoboy** [comment]
I'm going to assume you're not talking about JS Blocker since it doesn't have what you're talking about.
