### ISSUE TITLE
the toolbar icon badging should be updated only for the current window

### ISSUE THREAD

**Issue by MartySkinner** [infernoboy/JavaScript-Blocker#18]
Whenever a tab loads, this extension updates its toolbar badge count in the current window, and in all other windows. To better reflect the status of the "stats" from the current tab, the update should be limited to only the window in which this tab is viewable. Other Safari extensions seem to handle this differently: DoNotTrackMe, AdBlock, etc. See the screenshot showing DoNotTrackMe being appropriate for the visible tab within each window.

![safari toolbar badges](https://f.cloud.github.com/assets/397975/852931/27a9c0ea-f4c3-11e2-9163-295a4497d179.png)

**Comment by infernoboy** [comment]
This issue will be resolved in the next update, 3.4.0.
