### ISSUE TITLE
Massive memory leak with Safari 6.0.5

### ISSUE THREAD

**Issue by retsyx** [infernoboy/JavaScript-Blocker#20]
I noticed Safari was leaking memory like mad (consuming all available memory after an hour or two of usage).
I disabled JavaScript-Blocker and and the memory leak went away.

Other extensions in use (and still enabled) are:

AdBlock
ClickToFlash
Incognito

**Comment by infernoboy** [comment]
This is occurring with the latest release, 3.4.0? How many rules do you have?

**Comment by retsyx** [comment]
This happens with 3.4.0 (I let Safari auto-update)
I have no rules that I'm aware of. I just install and use it as is.

**Comment by infernoboy** [comment]
Any Other Features enabled from the settings page? It's quite difficult to debug a memory issue like this.

**Comment by retsyx** [comment]
No, I just vanilla install.

**Comment by infernoboy** [comment]
Hm, there does seem to be an issue with the rule cache forever growing: 
![screen-shot-2013-08-19-at-9 22 50-am](https://f.cloud.github.com/assets/25857/986143/8483a088-08d2-11e3-8b97-bf23947f73f6.png)

I'll be looking into this.

**Comment by retsyx** [comment]
If you need me to run any kinds of tests (like looking at rule cache growth or clearing it when memory is maxed out), just let me know (along with instructions).

**Comment by infernoboy** [comment]
Unfortunately those buttons are not available in 3.4.0. I just added them and they will be available in the next update, 4.0.0. I don't know when it will be ready, though.

**Comment by infernoboy** [comment]
If possible, when the memory usage seems abnormally high, could you run this from the popover's Web Inspector window?

``` javascript
JSB = GlobalPage.page().JB; JSB.utils.bsize(JSON.stringify(JSB.rules.cache).length);
```

You'll need to have the Develop menu enabled (Safari preferences > Advanced > Show Develop in Menu Bar), then open the popover, right-click/cmd-click anywhere in it, and choose Inspect Element. From there, open the console: 
![screen-shot-2013-08-19-at-1 39 45-pm](https://f.cloud.github.com/assets/25857/987881/75db9436-08f6-11e3-8a2c-037e8cd44043.png)

You might have to click Current Log when it appears on the left. Then, on the right side near the bottom of the window near the blue >, click and paste the code above and hit return. Preferably, the result should be around 3MB; after the fixes I implemented for 4.0.0 this is the result I see.

**Comment by retsyx** [comment]
I get the error:

ReferenceError: Can't find variable: GlobalPage

**Comment by infernoboy** [comment]
Sorry it has taken so long to reply!

Has version 4.0.4 improved this at all?
