### ISSUE TITLE
Can't upgrade to 4.0.9.3

### ISSUE THREAD

**Issue by rnapier** [infernoboy/JavaScript-Blocker#22]
I have 4.0.9.2 installed. When I try to upgrade to 4.0.9.3, it fails with "An error occurred while installing the extension “JavaScript Blocker”."

Safari: Version 7.0 (9537.71)
OS X 10.9 (13A603)

**Comment by infernoboy** [comment]
Not sure if it'll help, but I rebuilt the extension file. See if the update completes successfully now. If not, you can download it manually and install it over the older version. I'm not sure why this happens.

**Comment by rnapier** [comment]
Thanks. 4.1 upgraded fine. Greasemonkey… very nice. Sent another small
paypal for the tip jar. That's great work.
