### ISSUE TITLE
Enable/Disable scripts feature request

### ISSUE THREAD

**Issue by ldong** [infernoboy/JavaScript-Blocker#24]
After we added user scripts in JavaScript Blocker, it would be nice to enable and disable certain scripts of them, rather than delete the scripts permanently.

Right now we could do that with `include` in the userscript files' header, but this feature would be nice to have, making much easier to enable/disable scripts.

**Comment by infernoboy** [comment]
JavaScript Blocker 4 is no longer receiving feature updates. This feature will be available in the upcoming JavaScript Blocker 5 release.
