### ISSUE TITLE
Constant hidden feature reminder

### ISSUE THREAD

**Issue by KatieKeys** [infernoboy/JavaScript-Blocker#28]
Every time you click the toolbar icon you are reminded of the new 4.1.14 hidden feature setting even though the hide blacklists and whitelists checkbox is not checked in user setings. Then you can only proceed by clicking on the hidden features tab. Extremely annoying!

**Comment by infernoboy** [comment]
This issue has finally been resolved after receiving the console log that was in my junk folder…
