### ISSUE TITLE
GM_xmlhttpRequest compatibility

### ISSUE THREAD

**Issue by ccd0** [infernoboy/JavaScript-Blocker#35]
I came across two differences with Greasemonkey's `GM_xmlhttpRequest` while getting a userscript to work in JS Blocker:
- The `responseHeaders` member of the response object is an object containing headers as key/value pairs whereas Greasemonkey provides the unparsed string from `getAllResponseHeaders()`.  The former is probably more useful, but if it's provided, it should be under a different name.
- `overrideMimeType` isn't supported, although the same functionality seems to be available through `mimeType`.  This is useful for downloading binary data using the `"text/plain; charset=x-user-defined"` MIME type override hack.

**Comment by infernoboy** [comment]
Ah, I did not realize that it didn't parse it into an object. I will be changing it return the string and move the object version over to `responseHeadersObject`.

I will be adding support for `overrideMimeType`.

**Comment by infernoboy** [comment]
Whoops, did not realize this issue was opened for version 4. I don't think I'll be updating 4 with these changes, but they will be made in version 5.

**Comment by ccd0** [comment]
Oops.  Yes, I meant to open this in version 5.  I didn't notice there were two repositories.
