### ISSUE TITLE
Option to allow resources from subdomains

### ISSUE THREAD

**Issue by m-urban** [infernoboy/JavaScript-Blocker#36]
Hi there,

First of all I would like to thank all the people involved for this great extension. It basically completed my process of ditching Firefox with its NoScript add-on.

Now I have got a question regarding the configuration: Is there a way to automatically allow resources from all subdomains of the current domain I am on?
For example, it happens frequently that I want to access pages like `example.com` and it wants to load scripts or images from `www.example.com` or `cdn.example.com` and the like. I always need to unblock both subdomains then. Is there an automatic way to always allow resources from subdomains of the same parent domain?

**Comment by infernoboy** [comment]
Thank you. 

You can manage that from the Rules tab of the Settings page. Each resource type is individually controlled.

**Comment by m-urban** [comment]
Nice! I hadn't quite realized that I needed to "trust" domains first (or change the "Block all resources on unknown…" setting). I have got everything set up now, thanks!

**Comment by infernoboy** [comment]
Oh I thought you were talking about JSB 4 since this is the github for that.
