### ISSUE TITLE
Can't delete custom rules

### ISSUE THREAD

**Issue by bjartskular** [infernoboy/JavaScript-Blocker#37]
When I create a custom rule for a page from the page tab, I cannot delete it from the rules page. I can click the delete button to the right of the rule and the delete button will light up like its trying to do something, but after a few seconds the button will go back to the way it was before and the rule will remain.

**Comment by bjartskular** [comment]
Just realized that this is for version 4 and I am running version 5.

**Comment by infernoboy** [comment]
Either way, you have to click delete twice. Once to make it turn red, again to confirm the deletion.
