### ISSUE TITLE
Firefox input field cannot be selected by mouse

### ISSUE THREAD

**Issue by OEN007** [infernoboy/JavaScript-Blocker#7]
Input field text is no longer markable (field is selectable but text is not markable) by mouse when popover is active (displayed), although mark by keyboard works fine.

firefox 8.0 (but have observed this on most versions)

**Comment by infernoboy** [comment]
I'm a bit confused. How does Firefox come into play for this Safari extension.

**Comment by OEN007** [comment]
Travis, I'm sorry for this confusion, this ticket was for Twitter Bootstrap. 
However, realizing my mistake I just closed the issue as I'm not able to actually erase it.
