### ISSUE TITLE
Block all by default, allow by host

### ISSUE THREAD

**Issue by petri** [infernoboy/JavaScript-Blocker#8]
The interface really needs to work like NoScript's. Block all by default (or better, block all coming from different domain) and have a by-domain checkbox dropdown for enabling domain by domain. That's really all most of the users need.

Seems to me this cannot be done now - at least very easily - or then I just don't understand the user interface myself :)

**Comment by infernoboy** [comment]
As of the 1.5 update, the default interfaced has been changed to simple mode. This shows just the hostnames, like NoScript. Just click on allow or block twice to trigger the action. Also, allow mode is the new default with automatic rules to block scripts from other hostnames; just like you said. Only scripts from the same hosts are allowed.

A normal user will never have to see the rules interface unless they want to. I originally created this as a personal project so I didn't think of over simplifying it. I will, however, continue to work on making the interface simpler and easier to use in the future.

**Comment by infernoboy** [comment]
When you said "by-domain checkbox drop down for enabling domain by domain" is this what you mean?

http://i.imgur.com/2ohcl.png

**Comment by infernoboy** [comment]
I believe the 2.0.0 update should satisfy the needs of this issue.

**Comment by petri** [comment]
Yes. Thanks!
